name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/pmiscisz/weather-app
  CACHE_REPO: ziabas/weather-app-cache

jobs:
  build-and-push:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub for cache
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push with cache
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
        cache-from: type=registry,ref=${{ env.CACHE_REPO }}:cache
        cache-to: type=registry,ref=${{ env.CACHE_REPO }}:cache,mode=max

    - name: Scan image with Trivy
    uses: aquasecurity/trivy-action@master
    env:
      TRIVY_USERNAME: ${{ github.actor }}
      TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      image-ref: ${{ env.IMAGE_NAME }}:latest
      format: 'table'
      exit-code: '1'
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'

